### ISSUE TITLE
Wrong formula applied in Loss of Integrity --> All data totally corrupt [9]

### ISSUE THREAD

**Issue by talk2noob** [tanprathan/OWASP-Testing-Checklist#3]
Please fix formula applied in **Loss of Integrity --> All data totally corrupt [9]** 

_from_ 

> =VLOOKUP(G6,References!C$11:D$16,2,FALSE)

_to_ 

> =VLOOKUP(G6,References!C$11:D$17,2,FALSE)

**Comment by tanprathan** [comment]
Fixed
